image: debian/bullseye
sources:
  - https://github.com/brenns10/sos
tasks:
 - packages:
   - build-essential
   - qemu-system-arm
   - gcc-arm-none-eabi
   - gcovr
   - mtools
   - python3-pytest
 - build: |
     cd sos
     make config_qemu
     make all
 - test: |
     cd sos
     make test
