image: debian/stable
packages:
 - build-essential
 - qemu-system-arm
 - gcc-arm-none-eabi
 - libpixman-1-dev
 - gcovr
 - python3
 - python3-pytest
tasks:
 - build: |
     cd sos
     make all
 - test: |
     cd sos
     make test
