image: debian/bullseye
packages:
 - build-essential
 - qemu-system-arm
 - gcc-arm-none-eabi
 - gcovr
 - mtools
 - python3
 - python3-pytest
sources:
  - https://github.com/brenns10/sos
tasks:
 - build: |
     cd sos
     make config_qemu
     make all
 - test: |
     cd sos
     make test
